{
 "title": "Flow Rate",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mock_tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flowmeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reading\" or r[\"_field\"] == \"setpoint\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"0\")\r\n"
    }
   ]
  },
  {
   "title": "Proportional Valve",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mock_tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"proportional valve\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"set\" or r[\"type\"] == \"current\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"0\")\r\n"
    }
   ]
  },
  {
   "title": "PID Control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mock_tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PID\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"D\" or r[\"_field\"] == \"I\" or r[\"_field\"] == \"P\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"0\")\r\n"
    }
   ]
  }
 ]
}